### ISSUE TITLE
Update Saved WebMaps with new Vector Tile Layers

### ISSUE THREAD

**Issue by nixta** [Esri/geodev-hackerlabs#118]
I think this is the only saved map: http://www.arcgis.com/home/webmap/viewer.html?webmap=11e2285a131540f792c58565db996b4b

However, it uses the original beta vector tiles which are now flagged as Mature Support.

It should be updated with this: http://www.arcgis.com/home/item.html?id=bf79e422e9454565ae0cbe9553cf6471

BTW `owner:esri_vector -mature` is a great search term :)

I think @alaframboise has to do this.

**Comment by alaframboise** [comment]
Fixed.
