### ISSUE TITLE
Question about Extras in add_feature_layers_jsapi.md

### ISSUE THREAD

**Issue by andygup** [Esri/geodev-hackerlabs#121]
The second (last) bullet in [add_feature_layers_jsapi.md](https://github.com/Esri/geodev-hackerlabs/blob/gh-pages/develop/add_feature_layers_jsapi.md) is a tad confusing. 

Can we clarify in text what we want the developer to do on this step? Do they simply need to swap the addLayer() statements, or something more advanced such as using [Map.reoderLayer()](https://developers.arcgis.com/javascript/jsapi/map-amd.html#reorderlayer)?

**Comment by alaframboise** [comment]
Fixed #156
