### ISSUE TITLE
Clarify step 3

### ISSUE THREAD

**Issue by jsolly** [Esri/geodev-hackerlabs#137]
For step 3:
1. In the table of contents, hover over the selected layer and click More Options > Copy

You might want to mention that you have to hover over the three '•••' else, 'More options' will not appear.

**Comment by jgravois** [comment]
thanks for the feedback @jsolly!  you're referring to the lab below, correct?

https://github.com/Esri/geodev-hackerlabs/blob/gh-pages/design/customize_vector_map/lab.md

**Comment by jsolly** [comment]
yes @jgravois I must have put my comment in the wrong section. Woops!

**Comment by jgravois** [comment]
this is definitely the right place.  just needed a little clarification.  you can find a proposed fix in #140.  let me know if it seems sufficient.
