### ISSUE TITLE
Create a New 3D Scene: "Layer cannot be added"

### ISSUE THREAD

**Issue by garysheppardjr** [Esri/geodev-hackerlabs#145]
Follow the steps at https://github.com/Esri/geodev-hackerlabs/blob/gh-pages/design/create_a_new_3d_scene/lab.md to create a new 3D scene. Step 4.i. says to add a layer with the URL http://services.arcgis.com/uCXeTVveQzP4IIcx/arcgis/rest/services/PDX_Rail_Lines/FeatureServer/0 . But that layer is not added to the scene, and an error message appears:

![image](https://cloud.githubusercontent.com/assets/3091666/15777306/28563d04-295c-11e6-9147-99c1d20258a5.png)

> Layer cannot be added: PDX Rail Lines
> Unable to load http://services.arcgis.com/uCXeTVveQzP4IIcx/arcgis/rest/services/PDX_Rail_Lines/FeatureServer/0?f=json status: 0 http://services.arcgis.com/uCXeTVveQzP4IIcx/arcgis/rest/services/PDX_Rail_Lines/FeatureServer/0

I get a similar error message for http://services.arcgis.com/uCXeTVveQzP4IIcx/arcgis/rest/services/PDX_Rail_Stops/FeatureServer/0 .

**Comment by nixta** [comment]
OK. Here's what I think is happening. Your org is probably forcing you to run over HTTPS and the URLs above are only HTTP so Chrome is complaining because it breaks Chrome's rules. I'll update the lab to reference HTTPS URLs. Thanks for catching this!

**Comment by garysheppardjr** [comment]
@nixta, yes, it looks like that's all it is. If I use the same service URL but with HTTPS instead of HTTP, it works. I should have thought of that. #facepalm

**Comment by nixta** [comment]
Well, not really. This is a good catch for the crowd :)
