### ISSUE TITLE
Calcite Maps App lab: layers do not display

### ISSUE THREAD

**Issue by garysheppardjr** [Esri/geodev-hackerlabs#150]
Follow the steps in the [Calcite Maps App lab](https://github.com/Esri/geodev-hackerlabs/blob/gh-pages/develop/jsapi/create_calcite_maps_app/lab.md). The basemap displays, but the neighborhoods, rail lines, and rail stops layers do not display. The [completed app](http://esri.github.io/geodev-hackerlabs/develop/jsapi/create_calcite_maps_app/index.html) also has this issue, as does an app created from the [solution source code](https://github.com/Esri/geodev-hackerlabs/blob/gh-pages/develop/jsapi/create_calcite_maps_app/index.html).

In addition, some gray text appears over the top left corner of the map:

![image](https://cloud.githubusercontent.com/assets/3091666/15782847/c21610aa-2979-11e6-82ee-90657667d30d.png)

**Comment by alaframboise** [comment]
Yip, I plan to clean this up today. Calcite Maps got an overhaul and things need to be synced. Tks!

**Comment by alaframboise** [comment]
@garys-esri fixed with latest release and lab. Cheers!

@nixta
