### ISSUE TITLE
Design > Customize Vector Basemap (misspelling on step 7)

### ISSUE THREAD

**Issue by jsolly** [Esri/geodev-hackerlabs#154]
On step:
1. Go to arcgis.com and login if necessary. Click My Content > click the Light Green Canvas tile layer > click UPDATE > Choose File > select the root.json file > UPDATE ITEM.

-----"UPDATE ITEM" is actually called "Update Style File"-----

**Comment by nixta** [comment]
Fixed in https://github.com/Esri/geodev-hackerlabs/commit/ae6de842e4e1c9f27cfd484a762c58c37b9d5d31#diff-1efb10f4ee871ef71a5cf4fae048d2bf

Thanks!
