### ISSUE TITLE
Suggestion: Import Data

### ISSUE THREAD

**Issue by hhkaos** [Esri/geodev-hackerlabs#169]
Hi guys!

What about adding some sources to the [Import Data](https://github.com/Esri/geodev-hackerlabs/blob/gh-pages/data/import_data/lab.md) page, like our [Open Data Portal](http://opendata.arcgis.com) and **a few more** to help developers understand where they can find geolocated data?

**Comment by jgravois** [comment]
@hhkaos your ideas are always good, so there is no need to log issues to pitch them.  just PR away and we can start the discussion there!

**Comment by alaframboise** [comment]
@hhkaos I think this is a good idea and we could add a resource page or even a lab with links specifically for data resources. The only problem is that the lab instructions obviously wouldn't fit other datasets, but the general high-level steps still apply.

**Comment by jgravois** [comment]
i wrote a new lab on developers.arcgis.com called [_Discover Data_](https://developers.arcgis.com/labs/data/discover-data/) that borrows from this very good suggestion.
