### ISSUE TITLE
Consider advertising hackerlabs as Enterprise-ready.

### ISSUE THREAD

**Issue by sarasanchez** [Esri/geodev-hackerlabs#189]
Currently, Hackerlabs are advertised to an ArcGIS Online only audience. Many could also be conducted using ArcGIS Enterprise. Please consider adding a statement in the read-me that many labs can also be accomplished using ArcGIS Enterprise.

I found that a majority from the first two sections are either portal-ready or require just a few additional steps (e.g., hosting a web app locally vs. using online developer sandbox.)

As a starting point, it could be as simple as adding an asterisk in the Getting Started, step 1 like this:

Sign up for a free ArcGIS Developer subscription – Your subscription allows you to download software, register apps, import data, create new services, store maps, perform spatial analysis and more. If you already have an ArcGIS Organizational* subscription (with at least publisher level permission) you can use that too….

*If you are using ArcGIS Enterprise (including Portal for ArcGIS), you may also complete many of the labs as-is or with a few additional steps.

**Comment by jgravois** [comment]
addressed in 45353f9.  sorry it took us so long to see this!
