### ISSUE TITLE
Light Green Vector Basemap - Example Live Map does not load

### ISSUE THREAD

**Issue by carpealaska** [Esri/geodev-hackerlabs#190]
2. Design
"Customize Vector Basemap" lab

At the bottom after going through the lab - the "Live Map" link that is supposed to let you compare your map to, doesn't seem to load up. 
Layer name: "Light Green Canvas"

**Comment by dmartine** [comment]
I'll take a look and fix it. Thanks.

**Comment by jgravois** [comment]
fixed in a78bb55. thanks for reporting @carpealaska!
