### ISSUE TITLE
Update 3D scene lab for smart mapping capabilities

### ISSUE THREAD

**Issue by mzurn** [Esri/geodev-hackerlabs#191]
For the [3D scene lab](https://github.com/Esri/geodev-hackerlabs/blob/gh-pages/design/create_a_new_3d_scene/lab.md), it would be cool if you updated step 5ii (PXD rail stops) to use the [3D object drawing style](http://doc.arcgis.com/en/arcgis-online/create-maps/configure-layers-in-scene.htm#ESRI_SECTION1_DA1996687B1449D390244E95B70AAF1A).

**Comment by jgravois** [comment]
sounds like a good idea to me.  you game for submitting the change as a pull request?

**Comment by mzurn** [comment]
@jgravois - I think we need to work together on this? Here are the revised steps but I think you need to update the live example? 

5....
i.......
ii. Navigate back to your previous zoomed in/rotated view.
iii. Click PDX Rail Stops > Configure Layer > 3D Object>Options and change the following properties:
- Color: Red (pick a dark red with 25% transparency)
- Size: 80

**Comment by jgravois** [comment]
> I think you need to update the live example?

we can definitely update the live sample.  i was asking if you can submit a [pull request](https://help.github.com/articles/about-pull-requests/) with your proposed change. the easiest way to do with is probably to just use the live github.com editor in the browser.

https://help.github.com/articles/editing-files-in-your-repository/
https://guides.github.com/activities/contributing-to-open-source/

**Comment by mzurn** [comment]
@jgravois - done!

**Comment by jgravois** [comment]
closed via #192. thx!
