### ISSUE TITLE
use 'master' as default branch instead of 'gh-pages'

### ISSUE THREAD

**Issue by jgravois** [Esri/geodev-hackerlabs#214]
GitHub has supported hosting static pages from the [`master`](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/) branch for quite some time. lets make this repo more beginner friendly and take advantage of it.

i've already pushed a `master` branch up that is in sync with `gh-pages` and contains a lone commit that updates two relevant links.  someone with admin access to this repo just needs to: 

1. make `master` the default branch in the repo settings
2. ensure that we are using `master` to host our static pages (also in settings)
3. delete the `gh-pages` branch

**Comment by jgravois** [comment]
rebased content from #215 

@alaframboise, can you tackle this one when you have a couple minutes please?

**Comment by alaframboise** [comment]
@jgravois will do

**Comment by alaframboise** [comment]
Updated. Please verify and then I'll delete gh-pages.

**Comment by jgravois** [comment]
all done. thanks for humoring me.
