### ISSUE TITLE
Public Information Template missing 

### ISSUE THREAD

**Issue by JimBarry** [Esri/geodev-hackerlabs#39]
In the "Create a Template App" exercise, it asks you to choose the Public Information template. But that template doesn't seem to exist anymore(?)

**Comment by kellyhutchins** [comment]
The public information template still exists. Perhaps you have a custom template gallery setup in the org you used to test this with?

**Comment by jgravois** [comment]
@JimBarry not sure if you were using [edn.maps.arcgis](http://edn.maps.arcgis.com), but if so, i just reverted the Org to using the default Esri templates in:

> My Organization > Edit Settings > Map > Web App Templates

**Comment by JimBarry** [comment]
At the time, I was using my own ArcGIS Online Dev&Testing subscription. I don't remember doing anything with setting up a custom template gallery. I think I'm working with the default, but I'll look into it further to see why I can't get at it. Good chance there are other templates I can't get to either. I probably broke something on my end somehow.

**Comment by jgravois** [comment]
happy to chat about his more if it'd be helpful, but closing for now.
