### ISSUE TITLE
should setting up a github account and forking be included in the steps to get started?

### ISSUE THREAD

**Issue by jgravois** [Esri/geodev-hackerlabs#43]
seems like this should be 'optional'

**Comment by alaframboise** [comment]
Yip, it is optional now that they can access the .zip and it contains all the data they need. Need to updated instructions.

**Comment by jgravois** [comment]
let me do this one, i'm toying around with a few formatting changes at the same time.

**Comment by alaframboise** [comment]
Removed fork-clone requirement. Can download data straight from rawgit. #49
