### ISSUE TITLE
Changing description on meetup.com events 

### ISSUE THREAD

**Issue by JimBarry** [Esri/geodev-hackerlabs#48]
Dave Martinez and I worked on re-writing the description that we post out onto meetup.com so that it better reflects what attendees can expect to do at a HackerLab and why, which will better prepare them, and will better attract those who can learn what we're doing. For example, I removed the requirement that attendees much have a Github account and Git installed. That was setting the wrong impression for those going to HackerLabs and especially those who decided because of it that they wouldn't go or that it wasn't for them. Take a look at the new description. Let's discuss improving it further:

http://www.meetup.com/DevMeetUpNortheast/events/226818553/

**Comment by jgravois** [comment]
w/ regard to the repo, i think we'd all agree that most of the time signing up for a github account isn't helpful and that its putting the cart before the horse to ask people to search for/join our `Geodev Hackerlabs Share` group before they've even started working on a project.

i'll take a stab at simplifying the steps [here](https://github.com/Esri/geodev-hackerlabs/blob/gh-pages/README.md#getting-started), it'd be helpful to get some feedback.

as a seperate action item, i don't know whether keeping boilerplate for meetup announcements somewhere here is more helpful than just copy/pasting from the previous event. if so, it wouldn't be hard to find somewhere to stash it. i'd even be game for cribbing some of whats in jim's announcement and moving it right into our README.

**Comment by andygup** [comment]
I'm not sure I agree with this. Maybe I'm missing something as related specifically to Labs Section 3. I see two ways for developers to work this Section, specifically. They can either download the repo as a zip or they can use github which is the platform on which the repo resides in the first place. 

Rather than completely sanitizing any mention of github, I suggest we clarify why getting a github account is an **option** as related to Section 3, or they can download the zip file?

**Comment by jgravois** [comment]
i've yet to see anyone even download the `.zip`.  in my own experience, people just traverse the tutorials and copy/paste code as needed.

that being said, i don't think there's any harm in outlining alternative options.  i just think that the information is overkill when its the first thing people see.

**Comment by andygup** [comment]
I should have clarified. I'm talking about the README. 

How about something like this?
1. Sign up for an [ArcGIS Developer subscription](https://developers.arcgis.com/en/sign-up/).
2. Login to [ArcGIS Online](http://arcgis.com).
   - Search for `Geodev Hackerlabs Share` > `Search Groups`.
   - Uncheck `Only search in my account/organization`.
   - Join the group.
3. OPTIONAL: Sign up for a GitHub account if you don't have one.

**Comment by jgravois** [comment]
i was thinking something more like:

## Getting Started

Follow these steps to prepare for the labs.
1. Sign up for a **free** [ArcGIS Developer subscription](https://developers.arcgis.com/en/sign-up/).
2. ~~Login to [ArcGIS Online](http://arcgis.com).~~
   - ~~...~~
3. ~~Sign up for a GitHub account if you don't have one.~~

> then somewhere much further down...

## Want to share your work?
1. Login to [ArcGIS Online](http://arcgis.com).
   - Search for `Geodev Hackerlabs Share` > `Search Groups`.
   - Uncheck `Only search in my account/organization`.
   - Join the group.
   - share your item (include screenshot)

## Want to contribute?
1. Sign up for a GitHub account if you don't already have one.
2. Let us know what works and what doesn't in [an issue](https://github.com/Esri/geodev-hackerlabs/issues/new)
3. If you're already savvy with git (or want an excuse to start learning), feel free to fork the repo and send us a pull request!  (linking to some boilerplate doc would be helpful here)

**Comment by andygup** [comment]
I like it, good suggestion. Let's see what the other folks say.

**Comment by JimBarry** [comment]
Talked to AL more about this. For HackerLabs after this Boston one tomorrow (12/2), I like his idea of editing the meetup.com event page's Description so that it is much smaller and concise, less details there, and pushing all the details into the readme.md.

**Comment by JimBarry** [comment]
As for Github, sounds like there's a middle ground here. We don't want to push too hard that using Git/Github is required, but we can say that if you have a Github account, we encourage you to fork the repo rather than just downloading the zip. Also, having a Github account will allow you to report and discuss issues, and even contribute back to the project if you want. etc etc

**Comment by andygup** [comment]
I think that rewording is fair. Github isn't required, it's simply encouraged.

**Comment by jgravois** [comment]
closing this as resolved, but happy to chat further if anyone wants to.

fyi, just pushed 0e997eb to fix a couple typos in the README.
