### ISSUE TITLE
styled neighborhoods

### ISSUE THREAD

**Issue by jgravois** [Esri/geodev-hackerlabs#53]
you might just not have gotten around to it yet, but [this](http://edn.maps.arcgis.com/home/item.html?id=a0c6253a699345c39c30a9850a9bbed7) layer is titled 'styled' but still just has a simpleRenderer.

**Comment by alaframboise** [comment]
ya, it's just simple render, but it is styled

**Comment by jgravois** [comment]
oh, got confused by the unique value renderer thumbnail.
