### ISSUE TITLE
Broken leaflet link

### ISSUE THREAD

**Issue by augaug** [Esri/geodev-hackerlabs#6]
https://github.com/Esri/geodev-hackerlabs/blob/gh-pages/src/build_starter_map_leaflet.html

This link is bad, 2nd exercise in leaflet tutorials...

**Comment by jgravois** [comment]
thanks for that, i'll get it fixed.

the actual link is https://github.com/Esri/geodev-hackerlabs/blob/gh-pages/develop/src/esri_leaflet_starter.html
