### ISSUE TITLE
Esri-leaflet sample code link broken

### ISSUE THREAD

**Issue by alaframboise** [Esri/geodev-hackerlabs#60]
2. Use the code in http://esri.github.io/esri-leaflet/examples/renderers-plugin.html as a jumping off point.

@jgravois

**Comment by jgravois** [comment]
not sure what you're talking about.  that link loads fine for me.

**Comment by alaframboise** [comment]
Done.  https://github.com/Esri/geodev-hackerlabs/commit/603d320029134d49ef71011dc13ab3e0df9938d4
