### ISSUE TITLE
Fix steps for create authenticated traffic layer

### ISSUE THREAD

**Issue by dmartine** [Esri/geodev-hackerlabs#61]
Click My Contents > My Traffic Layer > Advanced Options select Limit Usage and set the checkbox to enable rate limiting to 1000 requests per second.

It is now refresh interval with the newest ArcGIS Online update.

**Comment by nixta** [comment]
Hmmm. Doesn't seem to be (did they revert?). Closing.

![2016-06-06_14-18-56](https://cloud.githubusercontent.com/assets/25374/15832745/9ecc06de-2bf1-11e6-8c26-635d3453f9f0.png)
