### ISSUE TITLE
Web map not public?

### ISSUE THREAD

**Issue by andygup** [Esri/geodev-hackerlabs#61]
@alaframboise Can you check that the [web map](http://edn.maps.arcgis.com/home/webmap/viewer.html?webmap=27970d32436a446dabb3c71cf949115e) in Step 1 of Create a Configurable Template App is public?

After I clicked on it I tried to sign in with my own account and got the following error message "The username you entered is not a member of this organization."

**Comment by andygup** [comment]
FYI, I'm not sure I have an account on the EDN org. @alaframboise Can you/someone verify? Otherwise I'd check on the web map's sharing config myself.

**Comment by andygup** [comment]
Same issue in Create a WAB App lab. If you try to use the web map, when you go to sign in you have to be a member of the EDN org.

**Comment by jgravois** [comment]
*andyedn* and *andygup2* are both members of the org.

**Comment by andygup** [comment]
@jgravois or @alaframboise Looks like none of the passwords or password hints I wrote down are working so I'm locked out for now. Can one of you do an admin reset on _andygup2_?

**Comment by jgravois** [comment]
no prob.  done.

**Comment by andygup** [comment]
Thanks!

**Comment by alaframboise** [comment]
This can be avoided by replacing:

http://edn.maps.arcgis.com/home/webmap/viewer.html?webmap=27970d32436a446dabb3c71cf949115e

with 

http://www.arcgis.com/home/webmap/viewer.html?webmap=27970d32436a446dabb3c71cf949115e 

Need to update all links.
