### ISSUE TITLE
outline for event at UC Berkeley on 1/15

### ISSUE THREAD

**Issue by jgravois** [Esri/geodev-hackerlabs#62]
### introduction (30 min) - @alaframboise
1. navigate this repo
2. navigate developer site (and AGOL)
3. vouchers
### data (1 hour) - @alaframboise
1. publish dataset from .zipped shapefile
2. create new empty schema
3. run drivetime/buffer/etc. analysis in AGOL
### design (1 hour) - @alaframboise
1. use Map Viewer to define advanced symbology on layer
### develop (1 hour)
1. demo publishing templates/wab from Map Viewer - @alaframboise 
2. set up local webserver - @jgravois
### develop (4 hours)
1. make an esri leaflet app to share the services created in the morning - @jgravois

**Comment by JimBarry** [comment]
This looks great John, thanks. On the one hand, they want to see open source projects that are built with or work with ArcGIS, but they also want a good look at other new (last 8-12 months) developments in ArcGIS that developers can use (ie, 3D, smart mapping, geometry engine). Not that you need to cover all that in-depth, but even if you touch on some of it and point them in the right direction. Also try to be prepared to take the lab in directions that you might only discover after you're there and talking to them.

**Comment by jgravois** [comment]
> Also try to be prepared to take the lab in directions that you might only discover after you're there and talking to them

good advice.  that's why you're the man.
