### ISSUE TITLE
Simplify JS Client-Side Buffer Lab

### ISSUE THREAD

**Issue by alaframboise** [Esri/geodev-hackerlabs#67]
We should probably remove the slider and make it an extra. This will be half the code.

https://github.com/Esri/geodev-hackerlabs/blob/gh-pages/develop/geometry_engine_buffer_jsapi.md

**Comment by nixta** [comment]
Didn't realize there was an issue for this. Fixed with commit https://github.com/Esri/geodev-hackerlabs/commit/593d5e1af2cc77d8e54736f0b6c509c70d8996f6
