### ISSUE TITLE
Text fix

### ISSUE THREAD

**Issue by PeregrineTEL** [Esri/geodev-hackerlabs#95]
Under Develop, JS API, Add a Vector Tile Layer Basemap exercise, Step 3, first line, says, 
"function(Map, FeatureLayer) {  "

It should say, 
"function(Map, FeatureLayer) { "

**Comment by dmartine** [comment]
Yes we need to change this title to add a vector tile layer and remove the FeatureLayer reference. Thanks.

**Comment by jgravois** [comment]
closed via a65065d971ce1a287085ed233d773f1db8b476ad
thanks for letting us know @PeregrineTEL!
