### ISSUE TITLE
Clarification needed in text, pls

### ISSUE THREAD

**Issue by PeregrineTEL** [Esri/geodev-hackerlabs#96]
While participating in the HackerLab, there was a surprise while working in the Data section, in the REST exercise. 
There was no explanation that one could not form a REST service from a KML file. I uploaded a KML instead of, say, a shapefile, and was confused when I clicked on the URL that resulted.

**Comment by andygup** [comment]
Thank you. We'll add a clarification and a link to the ArcGIS Online documentation.

**Comment by nixta** [comment]
After some chat with Andy, we think the Import Data lab could do with some clarification in the Bonus section.

What we're missing is that not all data will turn into a hosted service once uploaded. It's really an `Upload then Publish` process, but usefully rolled into one for `CSV`, `Shapefile`, `GeoJSON`, `File Geodatabase`, etc. (see [here](https://doc.arcgis.com/en/arcgis-online/share-maps/publish-features.htm)).

There is a [whole host of stuff](https://doc.arcgis.com/en/arcgis-online/share-maps/supported-items.htm) that can be added to ArcGIS Online as a CMS, but only very few of those things can then be published as hosted services.

KML ends up being a file that can be referenced and brought in as KML, but that's a read-once, process on client kind of thing. Effectively you download it from its ArcGIS Online Item URL and the client then represents it. Really [the interesting part in ArcGIS Online](https://doc.arcgis.com/en/arcgis-online/reference/kml.htm#ESRI_SECTION1_79EC75ECCE4B4AECB0DEB0CAA51386DB) is how the map viewer and APIs can handle it.

Let's try to succinctly express that in the Import Data lab's bonus section and maybe the REST lab's section too. Nothing lengthy. One sentence and some links should be enough.

**Comment by jgravois** [comment]
long overdue. thanks for the feedback @PeregrineTEL!
