### ISSUE TITLE
missing curly bracket Custom Widget step 6

### ISSUE THREAD

**Issue by HeidiSBeaverton** [Esri/geodev-hackerlabs#97]
Under the Web App Builder Custom Widget, step 6. there is a missing ending curly bracket. I spent a long time trying to figure out why this wasn't working! thanks

**Comment by andygup** [comment]
Thanks for the heads-up, we'll take a look!

**Comment by jgravois** [comment]
closed via 7f4cdc3f5d1159032a06052167a9f22cbbaec120

thanks for taking the time to report and sorry for the confusion @suname33!
